name: TCP proxy pipelines
on:
  push:
    branches: ["main"]
    tags:
      - v**
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.svg'
  pull_request:
    branches: ["main"]
    types: 
      - opened
      - synchronize
      - ready_for_review
    paths-ignore:
        - '**.md'
        - '**.png'
        - '**.svg'

env:
  # optional (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  CompileAndTest:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 2
      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        if: false
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}